// docs/.vitepress/theme/components/Quiz.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, nextTick, watch } from 'vue'
import { useProgress } from '../composables/useProgress'

interface QuizQuestion {
  id?: string
  stem: string
  options: string[]
  answer: string
  analysis: string
  chapter?: string | number
  isKey?: boolean
  isHot?: boolean
}

const props = defineProps<{
  questions?: QuizQuestion[]
  dataUrl?: string
  initialChapter?: string | number
}>()

const allQuestions = ref<QuizQuestion[]>([])
const currentIndex = ref(0)
const selected = ref<number | null>(null)
const showResult = ref(false)
const score = ref(0)
const answers = ref<Map<string, number | null>>(new Map())  // question id -> user's answer index
const filterChapter = ref<string>(props.initialChapter ? String(props.initialChapter) : '')
const chapters = ref<string[]>([])
const bookmarks = ref<Set<string>>(new Set())  // bookmarked question IDs
const showBookmarkOnly = ref(false)
const storageKey = 'quiz_progress_' + (props.dataUrl || 'inline')
const containerRef = ref<HTMLElement | null>(null)

// ---- localStorage helpers ----
function loadProgress() {
  try {
    const raw = localStorage.getItem(storageKey)
    if (raw) {
      const data = JSON.parse(raw)
      score.value = data.score || 0
      currentIndex.value = data.currentIndex || 0
      if (data.answers) answers.value = new Map(data.answers)
      if (data.bookmarks) bookmarks.value = new Set(data.bookmarks)
      // Migrate legacy data keyed by view index -> question id
      const ids = allQuestions.value.map(q => getQuestionId(q))
      let migrated = false
      answers.value.forEach((ans, key) => {
        if (/^\d+$/.test(String(key))) {
          const idx = Number(key)
          if (idx < ids.length) {
            answers.value.set(ids[idx], ans)
          }
          answers.value.delete(key)
          migrated = true
        }
      })
      if (migrated) saveProgress()
    }
  } catch { /* ignore corrupt data */ }
}

function saveProgress() {
  try {
    localStorage.setItem(storageKey, JSON.stringify({
      score: score.value,
      currentIndex: currentIndex.value,
      answers: Array.from(answers.value.entries()),
      bookmarks: Array.from(bookmarks.value),
      savedAt: Date.now()
    }))
  } catch { /* quota exceeded, ignore */ }
}

function clearProgress() {
  try { localStorage.removeItem(storageKey) } catch { /* ignore */ }
}

// ---- Load questions ----
onMounted(async () => {
  if (props.questions && props.questions.length > 0) {
    allQuestions.value = props.questions
  } else if (props.dataUrl) {
    try {
      const resp = await fetch(props.dataUrl)
      allQuestions.value = await resp.json()
    } catch (e) {
      console.error('Failed to load quiz data:', e)
    }
  }
  // Extract unique chapters
  const chapterSet = new Set(allQuestions.value.map(q => String(q.chapter)).filter(Boolean))
  chapters.value = Array.from(chapterSet)
  // Restore progress from localStorage
  loadProgress()
  // Jump to question referenced by URL hash (e.g. #softdesigner-001)
  const hashId = getHashQuestionId()
  if (hashId) {
    jumpToQuestionId(hashId)
  } else {
    restoreStateForCurrent()
  }
  window.addEventListener('hashchange', onHashChange)
})

onUnmounted(() => {
  window.removeEventListener('hashchange', onHashChange)
})

function getHashQuestionId(): string | null {
  const m = window.location.hash.match(/#([A-Za-z0-9_-]+-\d+)/)
  return m ? m[1] : null
}

function onHashChange() {
  const hashId = getHashQuestionId()
  if (hashId) {
    jumpToQuestionId(hashId)
  }
}

function jumpToQuestionId(id: string) {
  const q = allQuestions.value.find(item => getQuestionId(item) === id)
  if (!q) return
  // Apply chapter filter first, then jump after the filter watch resets the index
  if (q.chapter) filterChapter.value = String(q.chapter)
  nextTick(() => {
    const fIdx = filteredQuestions.value.findIndex(item => getQuestionId(item) === id)
    if (fIdx !== -1) {
      currentIndex.value = fIdx
      restoreStateForCurrent()
      saveProgress()
      containerRef.value?.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
  })
}

// ---- Filtering ----
const filteredQuestions = computed(() => {
  let qs = allQuestions.value
  if (filterChapter.value) {
    const filterNum = Number(filterChapter.value)
    qs = qs.filter(q => Number(q.chapter) === filterNum)
  }
  if (showBookmarkOnly.value) {
    qs = qs.filter(q => bookmarks.value.has(getQuestionId(q)))
  }
  return qs
})

const currentQuestion = computed(() => filteredQuestions.value[currentIndex.value])
const totalQuestions = computed(() => filteredQuestions.value.length)

function getQuestionId(q: QuizQuestion, idx?: number): string {
  return q.id || `q${idx ?? currentIndex.value}`
}

const optionLabels = ['A', 'B', 'C', 'D', 'E', 'F']

// ---- Progress integration (global learning-progress dashboard) ----
const { recordAnswer } = useProgress()

function deriveSubjectId(): string | null {
  // e.g. /softdesigner/ch01.html -> 'softdesigner'; /securities/laws/quiz.html -> 'securities-laws'
  const path = window.location.pathname.replace(/\.html$/, '')
  const segments = path.split('/').filter(Boolean)
  segments.pop() // drop page filename
  return segments.length > 0 ? segments.join('-') : null
}

function recordGlobalProgress(q: QuizQuestion, answerLetter: string, isCorrect: boolean) {
  const subjectId = deriveSubjectId()
  if (!subjectId || !q.chapter || !q.stem) return
  try {
    recordAnswer(subjectId, String(q.chapter), q.stem, answerLetter, isCorrect)
  } catch { /* progress persistence is best-effort */ }
}

// ---- Interaction ----
function selectOption(index: number) {
  if (showResult.value) return
  selected.value = index
}

function submitAnswer() {
  if (selected.value === null) return
  showResult.value = true
  const q = currentQuestion.value
  const answerLetter = optionLabels[selected.value]
  const isCorrect = answerLetter === q.answer
  answers.value.set(getQuestionId(q), selected.value)
  if (isCorrect) {
    score.value++
  }
  recordGlobalProgress(q, answerLetter, isCorrect)
  saveProgress()
}

function nextQuestion() {
  if (currentIndex.value < totalQuestions.value - 1) {
    currentIndex.value++
    restoreStateForCurrent()
    saveProgress()
  }
}

function prevQuestion() {
  if (currentIndex.value > 0) {
    currentIndex.value--
    restoreStateForCurrent()
    saveProgress()
  }
}

function jumpToQuestion(idx: number) {
  currentIndex.value = idx
  restoreStateForCurrent()
  saveProgress()
}

function restoreStateForCurrent() {
  const q = currentQuestion.value
  if (!q) return
  const prev = answers.value.get(getQuestionId(q))
  if (prev !== undefined && prev !== null) {
    selected.value = prev
    showResult.value = true
  } else {
    selected.value = null
    showResult.value = false
  }
}

function resetQuiz() {
  currentIndex.value = 0
  selected.value = null
  showResult.value = false
  score.value = 0
  answers.value.clear()
  clearProgress()
}

function isCorrect(index: number): boolean {
  return showResult.value && optionLabels[index] === currentQuestion.value?.answer
}

function isWrong(index: number): boolean {
  return showResult.value && selected.value === index && optionLabels[index] !== currentQuestion.value?.answer
}

function toggleBookmark() {
  const id = getQuestionId(currentQuestion.value, currentIndex.value)
  if (bookmarks.value.has(id)) {
    bookmarks.value.delete(id)
  } else {
    bookmarks.value.add(id)
  }
  saveProgress()
}

function isBookmarked(): boolean {
  return bookmarks.value.has(getQuestionId(currentQuestion.value, currentIndex.value))
}

// ---- Progress stats ----
const answeredCount = computed(() => answers.value.size)
const accuracy = computed(() => {
  if (answeredCount.value === 0) return 0
  let correct = 0
  answers.value.forEach((ans, qid) => {
    const q = allQuestions.value.find(item => getQuestionId(item) === qid)
    if (q && ans !== null && ans !== undefined && optionLabels[ans] === q.answer) correct++
  })
  return Math.round((correct / answeredCount.value) * 100)
})

function getAnswerForQuestion(q: QuizQuestion): number | null | undefined {
  return answers.value.get(getQuestionId(q))
}

function isQuestionAnswered(q: QuizQuestion): boolean {
  const ans = getAnswerForQuestion(q)
  return ans !== undefined && ans !== null
}

function isQuestionCorrect(q: QuizQuestion): boolean {
  const ans = getAnswerForQuestion(q)
  return ans !== undefined && ans !== null && optionLabels[ans] === q.answer
}

// Reset index when filter changes
watch([filterChapter, showBookmarkOnly], () => {
  currentIndex.value = 0
  selected.value = null
  showResult.value = false
})

// On first load, restore current question state
watch(allQuestions, () => {
  if (allQuestions.value.length > 0) restoreStateForCurrent()
})
</script>

<template>
  <div class="quiz-container" ref="containerRef" v-if="allQuestions.length > 0">
    <!-- Header -->
    <div class="quiz-header">
      <div class="quiz-info">
        <span class="quiz-progress">{{ currentIndex + 1 }} / {{ totalQuestions }}</span>
        <span class="quiz-score">得分: {{ score }}</span>
        <span class="quiz-accuracy" v-if="answeredCount > 0">正确率: {{ accuracy }}%</span>
      </div>

      <div class="quiz-controls">
        <!-- Chapter filter -->
        <div class="quiz-filter" v-if="chapters.length > 1">
          <select v-model="filterChapter" class="chapter-select">
            <option value="">全部章节</option>
            <option v-for="ch in chapters" :key="ch" :value="ch">{{ ch }}</option>
          </select>
        </div>

        <!-- Bookmark toggle -->
        <button class="btn btn-icon" :class="{ active: showBookmarkOnly }" @click="showBookmarkOnly = !showBookmarkOnly" :title="showBookmarkOnly ? '显示全部' : '只看收藏'">
          ★
        </button>
      </div>
    </div>

    <!-- Progress bar -->
    <div class="quiz-progress-bar">
      <div class="fill" :style="{ width: ((currentIndex + 1) / totalQuestions * 100) + '%' }"></div>
    </div>

    <!-- Question card -->
    <div class="question-card" v-if="currentQuestion">
      <!-- Badges + Bookmark -->
      <div class="question-top-row">
        <div class="question-badges">
          <span v-if="currentQuestion.isKey" class="badge badge-key">重点</span>
          <span v-if="currentQuestion.isHot" class="badge badge-hot">高频</span>
          <span v-if="currentQuestion.chapter" class="badge badge-chapter">第 {{ currentQuestion.chapter }} 章</span>
        </div>
        <button class="btn-bookmark" :class="{ active: isBookmarked() }" @click="toggleBookmark" :title="isBookmarked() ? '取消收藏' : '收藏本题'">
          {{ isBookmarked() ? '★' : '☆' }}
        </button>
      </div>

      <!-- Stem -->
      <div class="question-stem">{{ currentQuestion.stem }}</div>

      <!-- Options -->
      <div class="options-list">
        <button
          v-for="(option, index) in currentQuestion.options"
          :key="index"
          class="option-item"
          :class="{
            'selected': selected === index && !showResult,
            'correct': isCorrect(index),
            'wrong': isWrong(index),
          }"
          @click="selectOption(index)"
        >
          <span class="option-label">{{ optionLabels[index] }}</span>
          <span class="option-text">{{ option }}</span>
          <span v-if="isCorrect(index)" class="option-icon">&#10003;</span>
          <span v-if="isWrong(index)" class="option-icon">&#10007;</span>
        </button>
      </div>

      <!-- Analysis -->
      <div class="analysis-box" v-if="showResult">
        <div class="analysis-title">解析</div>
        <div class="analysis-text">{{ currentQuestion.analysis }}</div>
      </div>
    </div>

    <!-- Actions -->
    <div class="quiz-actions">
      <button class="btn btn-secondary" @click="prevQuestion" :disabled="currentIndex === 0">
        上一题
      </button>
      <button
        v-if="!showResult"
        class="btn btn-primary"
        @click="submitAnswer"
        :disabled="selected === null"
      >
        提交答案
      </button>
      <button
        v-else-if="currentIndex < totalQuestions - 1"
        class="btn btn-primary"
        @click="nextQuestion"
      >
        下一题
      </button>
      <button v-else class="btn btn-success" @click="resetQuiz">
        重新开始
      </button>
      <button class="btn btn-ghost" @click="resetQuiz" title="清除答题记录">
        清除记录
      </button>
    </div>

    <!-- Question navigator (dots) -->
    <div class="quiz-navigator">
      <div class="navigator-title">题目导航 (已答 {{ answeredCount }}/{{ totalQuestions }})</div>
      <div class="navigator-dots">
        <button
          v-for="(q, idx) in filteredQuestions"
          :key="idx"
          class="nav-dot"
          :class="{
            current: idx === currentIndex,
            answered: isQuestionAnswered(q),
            correct: isQuestionCorrect(q),
            wrong: isQuestionAnswered(q) && !isQuestionCorrect(q),
            bookmarked: bookmarks.has(getQuestionId(q, idx))
          }"
          @click="jumpToQuestion(idx)"
          :title="`第 ${idx + 1} 题`"
        >
          {{ idx + 1 }}
        </button>
      </div>
    </div>

    <!-- Bookmark count -->
    <div class="bookmark-info" v-if="bookmarks.size > 0">
      <span>已收藏 {{ bookmarks.size }} 题</span>
    </div>
  </div>

  <!-- Empty state -->
  <div class="quiz-empty" v-else>
    <p>暂无题目数据</p>
  </div>
</template>

<style scoped>
.quiz-container {
  margin: 1.5rem 0;
  padding: 1.5rem;
  border-radius: 12px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg-soft);
}

.quiz-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.75rem;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.quiz-info {
  display: flex;
  gap: 1rem;
  font-size: 0.9rem;
  color: var(--vp-c-text-2);
}

.quiz-score {
  font-weight: 600;
  color: var(--vp-c-brand-1);
}

.quiz-accuracy {
  font-weight: 600;
  color: var(--vp-c-brand-2);
}

.quiz-controls {
  display: flex;
  gap: 0.5rem;
  align-items: center;
}

.btn-icon {
  width: 32px;
  height: 32px;
  border-radius: 8px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg);
  cursor: pointer;
  font-size: 1.1rem;
  transition: all 0.15s ease;
}

.btn-icon:hover { border-color: var(--vp-c-brand-1); }
.btn-icon.active { background: var(--vp-c-brand-1); color: #fff; }

.chapter-select {
  padding: 0.35rem 0.75rem;
  border-radius: 8px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg);
  color: var(--vp-c-text-1);
  font-size: 0.85rem;
  cursor: pointer;
}

.quiz-progress-bar {
  height: 4px;
  background: var(--vp-c-divider);
  border-radius: 2px;
  overflow: hidden;
  margin-bottom: 1.25rem;
}

.quiz-progress-bar .fill {
  height: 100%;
  background: linear-gradient(90deg, var(--vp-c-brand-1), var(--vp-c-brand-2));
  border-radius: 2px;
  transition: width 0.3s ease;
}

.question-card { margin-bottom: 1rem; }

.question-top-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.75rem;
}

.question-badges {
  display: flex;
  gap: 0.5rem;
}

.badge {
  display: inline-block;
  padding: 0.15rem 0.6rem;
  border-radius: 999px;
  font-size: 0.75rem;
  font-weight: 600;
}

.badge-key {
  background: var(--badge-key-bg);
  color: var(--badge-key-color);
  border: 1px solid var(--badge-key-border);
}

.badge-hot {
  background: var(--badge-hot-bg);
  color: var(--badge-hot-color);
  border: 1px solid var(--badge-hot-border);
}

.badge-chapter {
  background: var(--vp-c-brand-soft);
  color: var(--vp-c-brand-1);
  border: 1px solid var(--vp-c-brand-1);
}

.btn-bookmark {
  background: none;
  border: none;
  font-size: 1.4rem;
  cursor: pointer;
  color: var(--vp-c-text-3);
  transition: color 0.15s;
  padding: 0 0.25rem;
}

.btn-bookmark:hover { color: var(--vp-c-brand-1); }
.btn-bookmark.active { color: #f59e0b; }

.question-stem {
  font-size: 1.05rem;
  line-height: 1.8;
  margin-bottom: 1.25rem;
  font-weight: 500;
}

.options-list {
  display: flex;
  flex-direction: column;
  gap: 0.6rem;
}

.option-item {
  position: relative;
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.75rem 1rem;
  border-radius: 10px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg);
  cursor: pointer;
  transition: all 0.15s ease;
  text-align: left;
  font-size: 0.95rem;
  color: var(--vp-c-text-1);
}

.option-item:hover:not(.correct):not(.wrong) {
  border-color: var(--vp-c-brand-1);
  background: var(--vp-c-brand-soft);
}

.option-item.selected {
  border-color: var(--vp-c-brand-1);
  background: var(--vp-c-brand-soft);
}

.option-item.correct {
  border-color: var(--correct-border);
  background: var(--correct-bg);
  color: var(--correct-color);
}

.option-item.wrong {
  border-color: var(--wrong-border);
  background: var(--wrong-bg);
  color: var(--wrong-color);
}

.option-label {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background: var(--vp-c-divider);
  font-size: 0.8rem;
  font-weight: 600;
  flex-shrink: 0;
}

.option-item.selected .option-label { background: var(--vp-c-brand-1); color: #fff; }
.option-item.correct .option-label { background: var(--correct-color); color: #fff; }
.option-item.wrong .option-label { background: var(--wrong-color); color: #fff; }

.option-text { flex: 1; }
.option-icon { font-size: 1.1rem; font-weight: 700; }

.analysis-box {
  margin-top: 1rem;
  padding: 1rem 1.25rem;
  border-radius: 10px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg);
}

.analysis-title {
  font-weight: 600;
  font-size: 0.9rem;
  color: var(--vp-c-brand-1);
  margin-bottom: 0.5rem;
}

.analysis-text {
  font-size: 0.9rem;
  line-height: 1.7;
  color: var(--vp-c-text-2);
}

.quiz-actions {
  display: flex;
  justify-content: center;
  gap: 0.75rem;
  margin-top: 1rem;
  flex-wrap: wrap;
}

.btn {
  padding: 0.55rem 1.25rem;
  border-radius: 8px;
  border: 1px solid var(--vp-c-divider);
  font-size: 0.9rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.15s ease;
}

.btn:disabled { opacity: 0.5; cursor: not-allowed; }

.btn-primary { background: var(--vp-c-brand-1); color: #fff; border-color: var(--vp-c-brand-1); }
.btn-primary:hover:not(:disabled) { background: var(--vp-c-brand-2); }

.btn-secondary { background: var(--vp-c-bg); color: var(--vp-c-text-1); }
.btn-secondary:hover:not(:disabled) { border-color: var(--vp-c-brand-1); color: var(--vp-c-brand-1); }

.btn-success { background: var(--correct-color); color: #fff; border-color: var(--correct-color); }
.btn-success:hover:not(:disabled) { opacity: 0.9; }

.btn-ghost { background: transparent; color: var(--vp-c-text-3); font-size: 0.8rem; }
.btn-ghost:hover { color: var(--vp-c-text-1); }

/* Question navigator */
.quiz-navigator {
  margin-top: 1.25rem;
  padding-top: 1rem;
  border-top: 1px solid var(--vp-c-divider);
}

.navigator-title {
  font-size: 0.8rem;
  color: var(--vp-c-text-3);
  margin-bottom: 0.5rem;
}

.navigator-dots {
  display: flex;
  flex-wrap: wrap;
  gap: 0.35rem;
}

.nav-dot {
  width: 30px;
  height: 30px;
  border-radius: 6px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg);
  cursor: pointer;
  font-size: 0.7rem;
  font-weight: 600;
  color: var(--vp-c-text-2);
  transition: all 0.15s ease;
}

.nav-dot:hover { border-color: var(--vp-c-brand-1); transform: scale(1.1); }
.nav-dot.current { background: var(--vp-c-brand-1); color: #fff; border-color: var(--vp-c-brand-1); }
.nav-dot.answered.correct { background: var(--correct-bg); border-color: var(--correct-border); color: var(--correct-color); }
.nav-dot.answered.wrong { background: var(--wrong-bg); border-color: var(--wrong-border); color: var(--wrong-color); }
.nav-dot.bookmarked { box-shadow: 0 0 0 2px #f59e0b; }

.bookmark-info {
  margin-top: 0.5rem;
  font-size: 0.8rem;
  color: var(--vp-c-text-3);
  text-align: center;
}

.quiz-empty {
  padding: 2rem;
  text-align: center;
  color: var(--vp-c-text-3);
  border: 1px dashed var(--vp-c-divider);
  border-radius: 12px;
}

@media (max-width: 768px) {
  .quiz-container { padding: 1rem; margin: 1rem 0; border-radius: 8px; }
  .quiz-header { flex-direction: column; gap: 0.5rem; align-items: flex-start; }
  .question-stem { font-size: 0.95rem; line-height: 1.7; }
  .option-item { padding: 0.75rem; font-size: 0.9rem; }
  .option-label { width: 28px; height: 28px; font-size: 0.8rem; }
  .quiz-actions { flex-wrap: wrap; gap: 0.5rem; }
  .btn { padding: 0.6rem 0.9rem; font-size: 0.85rem; }
  .nav-dot { width: 26px; height: 26px; font-size: 0.65rem; }
}
</style>

// components/Quiz.tsx
'use client'

/**
 * 题库练习 —— 自 VitePress Quiz.vue 移植。
 * localStorage key 沿用 `quiz_progress_` + dataUrl（与旧站一致，数据无缝延续）；
 * dataUrl 仅用于存储键，题目数据由服务端构建时直接注入。
 * 增强：错题本回顾、键盘作答（A–D / 1–4 选择，↵ 提交，←→ 切题）。
 */
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { QuizQuestion } from '@/lib/content'
import { deriveSubjectId, recordAnswer } from '@/lib/progress'

const OPTION_LABELS = ['A', 'B', 'C', 'D', 'E', 'F']
const LETTER_KEYS = ['a', 'b', 'c', 'd', 'e', 'f']
const NUM_KEYS = ['1', '2', '3', '4', '5', '6']

function getQuestionId(q: QuizQuestion, idx: number): string {
  return q.id || `q${idx}`
}

function stripLabel(option: string): string {
  return option.replace(/^[A-F]\s*[.、．]\s*/, '')
}

export default function Quiz({
  questions,
  dataUrl,
  initialChapter,
}: {
  questions: QuizQuestion[]
  dataUrl?: string
  initialChapter?: string | number
}) {
  const storageKey = 'quiz_progress_' + (dataUrl || 'inline')
  const containerRef = useRef<HTMLDivElement>(null)

  const [answers, setAnswers] = useState<Map<string, number | null>>(new Map())
  const [bookmarks, setBookmarks] = useState<Set<string>>(new Set())
  const [currentIndex, setCurrentIndex] = useState(0)
  const [selected, setSelected] = useState<number | null>(null)
  const [showResult, setShowResult] = useState(false)
  const [score, setScore] = useState(0)
  const [filterChapter, setFilterChapter] = useState(
    initialChapter != null ? String(initialChapter) : '',
  )
  const [showBookmarkOnly, setShowBookmarkOnly] = useState(false)
  const [showWrongOnly, setShowWrongOnly] = useState(false)
  const [hydrated, setHydrated] = useState(false)

  const chapters = useMemo(
    () => [...new Set(questions.map((q) => String(q.chapter)).filter(Boolean))],
    [questions],
  )

  const filteredQuestions = useMemo(() => {
    let qs = questions
    if (filterChapter) qs = qs.filter((q) => Number(q.chapter) === Number(filterChapter))
    if (showBookmarkOnly) qs = qs.filter((q, i) => bookmarks.has(getQuestionId(q, i)))
    if (showWrongOnly)
      qs = qs.filter((q, i) => {
        const a = answers.get(getQuestionId(q, i))
        return a != null && OPTION_LABELS[a] !== q.answer
      })
    return qs
  }, [questions, filterChapter, showBookmarkOnly, showWrongOnly, bookmarks, answers])

  const currentQuestion = filteredQuestions[currentIndex]
  const totalQuestions = filteredQuestions.length

  const answeredCount = useMemo(
    () => [...answers.values()].filter((v) => v != null).length,
    [answers],
  )
  const wrongCount = useMemo(() => {
    let n = 0
    questions.forEach((q, i) => {
      const a = answers.get(getQuestionId(q, i))
      if (a != null && OPTION_LABELS[a] !== q.answer) n++
    })
    return n
  }, [questions, answers])
  const accuracy =
    answeredCount === 0
      ? 0
      : Math.round(((answeredCount - wrongShown(answers, questions)) / answeredCount) * 100)

  // ---- 状态恢复：当前题是否有历史作答 ----
  useEffect(() => {
    const q = filteredQuestions[currentIndex]
    if (!q) {
      setSelected(null)
      setShowResult(false)
      return
    }
    const prev = answers.get(getQuestionId(q, questions.indexOf(q)))
    if (prev != null) {
      setSelected(prev)
      setShowResult(true)
    } else {
      setSelected(null)
      setShowResult(false)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentIndex, filteredQuestions, answers])

  // ---- 筛选变化时回到第一题 ----
  useEffect(() => {
    setCurrentIndex(0)
  }, [filterChapter, showBookmarkOnly, showWrongOnly])

  // ---- 初次挂载：读取存储 + hash 深链 ----
  useEffect(() => {
    try {
      const raw = localStorage.getItem(storageKey)
      if (raw) {
        const data = JSON.parse(raw)
        const loaded = new Map<string, number | null>(data.answers || [])
        // 旧数据迁移：视图索引键 → questionId 键
        let migrated = false
        for (const [key, value] of [...loaded]) {
          if (/^\d+$/.test(String(key))) {
            const idx = Number(key)
            if (idx < questions.length) loaded.set(getQuestionId(questions[idx], idx), value)
            loaded.delete(key)
            migrated = true
          }
        }
        setAnswers(loaded)
        setBookmarks(new Set(data.bookmarks || []))
        setScore(data.score || 0)
        if (migrated || true) {
          // 迁移后立即回写
          try {
            localStorage.setItem(
              storageKey,
              JSON.stringify({
                score: data.score || 0,
                currentIndex: 0,
                answers: [...loaded],
                bookmarks: [...(data.bookmarks || [])],
                savedAt: Date.now(),
              }),
            )
          } catch {
            /* ignore */
          }
        }
      }
    } catch {
      /* 忽略损坏数据 */
    }
    setHydrated(true)

    const hashId = getHashQuestionId()
    if (hashId) jumpToQuestionId(hashId)
    window.addEventListener('hashchange', onHashChange)
    return () => window.removeEventListener('hashchange', onHashChange)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // ---- 任何状态变化自动持久化 ----
  useEffect(() => {
    if (!hydrated) return
    try {
      localStorage.setItem(
        storageKey,
        JSON.stringify({
          score,
          currentIndex,
          answers: [...answers],
          bookmarks: [...bookmarks],
          savedAt: Date.now(),
        }),
      )
    } catch {
      /* 配额超限，忽略 */
    }
  }, [hydrated, storageKey, score, currentIndex, answers, bookmarks])

  function getHashQuestionId(): string | null {
    const m = window.location.hash.match(/#([A-Za-z0-9_-]+-\d+)/)
    return m ? m[1] : null
  }

  function onHashChange() {
    const hashId = getHashQuestionId()
    if (hashId) jumpToQuestionId(hashId)
  }

  function jumpToQuestionId(id: string) {
    const idxInAll = questions.findIndex((q, i) => getQuestionId(q, i) === id)
    if (idxInAll === -1) return
    const q = questions[idxInAll]
    const chapterKey = q.chapter != null ? String(q.chapter) : ''
    let list = questions
    if (chapterKey) list = list.filter((x) => Number(x.chapter) === Number(chapterKey))
    if (showBookmarkOnly) list = list.filter((x, i) => bookmarks.has(getQuestionId(x, i)))
    if (showWrongOnly)
      list = list.filter((x, i) => {
        const a = answers.get(getQuestionId(x, i))
        return a != null && OPTION_LABELS[a] !== x.answer
      })
    const fIdx = list.findIndex((x) => getQuestionId(x, questions.indexOf(x)) === id)
    if (chapterKey) setFilterChapter(chapterKey)
    if (fIdx !== -1) setCurrentIndex(fIdx)
    containerRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  // ---- 全局学习进度联动 ----
  const recordGlobal = useCallback((q: QuizQuestion, answerLetter: string, isCorrect: boolean) => {
    if (typeof window === 'undefined') return
    const subjectId = deriveSubjectId(window.location.pathname)
    if (!subjectId || !q.chapter || !q.stem) return
    try {
      recordAnswer(subjectId, String(q.chapter), q.stem, answerLetter, isCorrect)
    } catch {
      /* 进度持久化尽力而为 */
    }
  }, [])

  // ---- 交互 ----
  const submitAnswer = useCallback(() => {
    const q = currentQuestion
    if (!q || selected === null || showResult) return
    const answerLetter = OPTION_LABELS[selected]
    const isCorrect = answerLetter === q.answer
    const id = getQuestionId(q, questions.indexOf(q))
    setAnswers((prev) => new Map(prev).set(id, selected))
    if (isCorrect) setScore((s) => s + 1)
    recordGlobal(q, answerLetter, isCorrect)
  }, [currentQuestion, selected, showResult, questions, recordGlobal])

  const nextQuestion = useCallback(() => {
    if (currentIndex < totalQuestions - 1) setCurrentIndex((i) => i + 1)
  }, [currentIndex, totalQuestions])

  const prevQuestion = useCallback(() => {
    if (currentIndex > 0) setCurrentIndex((i) => i - 1)
  }, [currentIndex])

  const jumpToQuestion = useCallback((idx: number) => setCurrentIndex(idx), [])

  function resetQuiz() {
    setCurrentIndex(0)
    setSelected(null)
    setShowResult(false)
    setScore(0)
    setAnswers(new Map())
    try {
      localStorage.removeItem(storageKey)
    } catch {
      /* ignore */
    }
  }

  function toggleBookmark() {
    if (!currentQuestion) return
    const id = getQuestionId(currentQuestion, questions.indexOf(currentQuestion))
    setBookmarks((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  const isCorrectOption = (index: number) =>
    showResult && currentQuestion && OPTION_LABELS[index] === currentQuestion.answer
  const isWrongOption = (index: number) =>
    showResult && selected === index && currentQuestion && OPTION_LABELS[index] !== currentQuestion.answer

  // ---- 键盘作答 ----
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const t = e.target as HTMLElement | null
      if (t && ['INPUT', 'SELECT', 'TEXTAREA'].includes(t.tagName)) return
      if (e.metaKey || e.ctrlKey || e.altKey) return
      if (!currentQuestion) return

      const key = e.key.toLowerCase()
      const optIdx = LETTER_KEYS.indexOf(key) >= 0 ? LETTER_KEYS.indexOf(key) : NUM_KEYS.indexOf(key)
      if (optIdx >= 0 && optIdx < currentQuestion.options.length && !showResult) {
        e.preventDefault()
        setSelected(optIdx)
        return
      }
      if (e.key === 'Enter') {
        if (!showResult) {
          e.preventDefault()
          submitAnswer()
        } else if (currentIndex < totalQuestions - 1) {
          e.preventDefault()
          nextQuestion()
        }
        return
      }
      if (e.key === 'ArrowRight') {
        e.preventDefault()
        nextQuestion()
      }
      if (e.key === 'ArrowLeft') {
        e.preventDefault()
        prevQuestion()
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [currentQuestion, showResult, submitAnswer, nextQuestion, prevQuestion, currentIndex, totalQuestions])

  if (questions.length === 0) {
    return (
      <div className="rounded-2xl border border-dashed border-line px-6 py-10 text-center text-ink-3">
        暂无题目数据
      </div>
    )
  }

  const bookmarked = currentQuestion
    ? bookmarks.has(getQuestionId(currentQuestion, questions.indexOf(currentQuestion)))
    : false

  return (
    <div ref={containerRef} className="glass rounded-2xl p-5 md:p-6">
      {/* 头部：统计 + 控制 */}
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-[13px] text-ink-2">
          <span className="font-medium tabular-nums text-ink">
            {currentIndex + 1} / {totalQuestions}
          </span>
          <span>
            得分 <span className="font-semibold tabular-nums text-accent">{score}</span>
          </span>
          {answeredCount > 0 && (
            <span>
              正确率 <span className="font-semibold tabular-nums text-accent">{accuracy}%</span>
            </span>
          )}
        </div>
        <div className="flex items-center gap-1.5">
          {chapters.length > 1 && (
            <select
              value={filterChapter}
              onChange={(e) => setFilterChapter(e.target.value)}
              className="h-8 rounded-lg border border-line bg-elev px-2 text-[12.5px] text-ink outline-none transition-colors hover:border-line-strong"
              aria-label="按章节筛选"
            >
              <option value="">全部章节</option>
              {chapters.map((ch) => (
                <option key={ch} value={ch}>
                  第 {ch} 章
                </option>
              ))}
            </select>
          )}
          <button
            onClick={() => {
              setShowWrongOnly((v) => !v)
              setShowBookmarkOnly(false)
            }}
            className={`h-8 rounded-lg border px-2.5 text-[12.5px] font-medium transition-colors ${
              showWrongOnly
                ? 'border-wrong/40 bg-wrong-bg text-wrong'
                : 'border-line bg-elev text-ink-2 hover:text-ink'
            }`}
            title="只看答错的题"
          >
            错题本{wrongCount > 0 ? ` ${wrongCount}` : ''}
          </button>
          <button
            onClick={() => {
              setShowBookmarkOnly((v) => !v)
              setShowWrongOnly(false)
            }}
            aria-label="只看收藏"
            title="只看收藏"
            className={`flex h-8 w-8 items-center justify-center rounded-lg border transition-colors ${
              showBookmarkOnly
                ? 'border-star/50 bg-star/10 text-star'
                : 'border-line bg-elev text-ink-3 hover:text-ink'
            }`}
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill={showBookmarkOnly ? 'currentColor' : 'none'} stroke="currentColor" strokeWidth="2" strokeLinejoin="round">
              <path d="m12 3 2.5 5.4 5.9.7-4.4 4 1.2 5.8L12 16l-5.2 2.9 1.2-5.8-4.4-4 5.9-.7Z" />
            </svg>
          </button>
        </div>
      </div>

      {/* 进度条 */}
      <div className="mb-5 h-1 overflow-hidden rounded-full bg-ink/[0.07] dark:bg-white/10">
        <div
          className="h-full rounded-full bg-gradient-to-r from-[#2997ff] to-[#5e5ce6] transition-[width] duration-300"
          style={{ width: `${((currentIndex + 1) / Math.max(totalQuestions, 1)) * 100}%` }}
        />
      </div>

      {currentQuestion ? (
        <>
          {/* 题干卡片 */}
          <div className="mb-1.5 flex items-start justify-between gap-3">
            <div className="flex flex-wrap gap-1.5">
              {currentQuestion.isKey && <Badge className="border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400">重点</Badge>}
              {currentQuestion.isHot && <Badge className="border-red-500/30 bg-red-500/10 text-red-600 dark:text-red-400">高频</Badge>}
              {currentQuestion.chapter != null && (
                <Badge className="border-line bg-elev text-ink-2">第 {currentQuestion.chapter} 章</Badge>
              )}
            </div>
            <button
              onClick={toggleBookmark}
              aria-label={bookmarked ? '取消收藏' : '收藏本题'}
              className={`shrink-0 rounded-lg p-1 transition-colors ${bookmarked ? 'text-star' : 'text-ink-3 hover:text-ink'}`}
            >
              <svg width="17" height="17" viewBox="0 0 24 24" fill={bookmarked ? 'currentColor' : 'none'} stroke="currentColor" strokeWidth="2" strokeLinejoin="round">
                <path d="m12 3 2.5 5.4 5.9.7-4.4 4 1.2 5.8L12 16l-5.2 2.9 1.2-5.8-4.4-4 5.9-.7Z" />
              </svg>
            </button>
          </div>

          <div className="mb-5 text-[16.5px] font-medium leading-[1.8] text-ink">{currentQuestion.stem}</div>

          {/* 选项 */}
          <div className="flex flex-col gap-2.5">
            {currentQuestion.options.map((option, index) => (
              <button
                key={index}
                onClick={() => !showResult && setSelected(index)}
                disabled={showResult}
                className={`flex items-center gap-3 rounded-xl border px-4 py-3 text-left text-[14.5px] leading-relaxed transition-all duration-150 ${
                  isCorrectOption(index)
                    ? 'border-correct/40 bg-correct-bg text-ink'
                    : isWrongOption(index)
                      ? 'border-wrong/40 bg-wrong-bg text-ink'
                      : selected === index
                        ? 'border-accent/50 bg-accent-soft text-ink'
                        : 'border-line bg-elev text-ink hover:border-accent/40'
                }`}
              >
                <span
                  className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[12.5px] font-semibold ${
                    isCorrectOption(index)
                      ? 'bg-correct text-white'
                      : isWrongOption(index)
                        ? 'bg-wrong text-white'
                        : selected === index
                          ? 'bg-accent text-white'
                          : 'bg-ink/[0.07] text-ink-2 dark:bg-white/10'
                  }`}
                >
                  {OPTION_LABELS[index]}
                </span>
                <span className="min-w-0 flex-1">{stripLabel(option)}</span>
                {isCorrectOption(index) && <CheckIcon className="text-correct" />}
                {isWrongOption(index) && <CrossIcon className="text-wrong" />}
              </button>
            ))}
          </div>

          {/* 解析 */}
          {showResult && currentQuestion && (
            <div className="mt-4 rounded-xl border border-line bg-elev p-4">
              <div className="mb-1.5 flex items-center gap-2 text-[13px] font-semibold text-accent">
                解析
                <span className="font-normal text-ink-3">
                  正确答案 {currentQuestion.answer}
                </span>
              </div>
              <p className="text-[14px] leading-[1.75] text-ink-2">{currentQuestion.analysis}</p>
            </div>
          )}
        </>
      ) : (
        <div className="rounded-xl border border-dashed border-line px-6 py-10 text-center text-[14px] text-ink-3">
          {totalQuestions === 0 && (showBookmarkOnly || showWrongOnly || filterChapter) ? (
            <>
              当前筛选没有题目
              <button
                onClick={() => {
                  setFilterChapter('')
                  setShowBookmarkOnly(false)
                  setShowWrongOnly(false)
                }}
                className="ml-2 text-accent hover:underline"
              >
                清除筛选
              </button>
            </>
          ) : (
            '暂无题目'
          )}
        </div>
      )}

      {/* 操作按钮 */}
      <div className="mt-5 flex flex-wrap items-center justify-center gap-2.5">
        <button
          onClick={prevQuestion}
          disabled={currentIndex === 0}
          className="h-9 rounded-lg border border-line bg-elev px-4 text-[13.5px] font-medium text-ink transition-colors hover:border-accent/50 hover:text-accent disabled:cursor-not-allowed disabled:opacity-40"
        >
          上一题
        </button>
        {!showResult ? (
          <button
            onClick={submitAnswer}
            disabled={selected === null}
            className="h-9 rounded-lg bg-accent px-5 text-[13.5px] font-medium text-white transition-colors hover:bg-accent/85 disabled:cursor-not-allowed disabled:opacity-40"
          >
            提交答案
          </button>
        ) : currentIndex < totalQuestions - 1 ? (
          <button
            onClick={nextQuestion}
            className="h-9 rounded-lg bg-accent px-5 text-[13.5px] font-medium text-white transition-colors hover:bg-accent/85"
          >
            下一题
          </button>
        ) : (
          <button
            onClick={resetQuiz}
            className="h-9 rounded-lg bg-correct px-5 text-[13.5px] font-medium text-white transition-opacity hover:opacity-90"
          >
            重新开始
          </button>
        )}
        <button
          onClick={resetQuiz}
          className="h-9 px-3 text-[12.5px] text-ink-3 transition-colors hover:text-ink"
          title="清除答题记录"
        >
          清除记录
        </button>
      </div>

      {/* 题目导航 */}
      <div className="mt-5 border-t border-line pt-4">
        <div className="mb-2 text-[12px] text-ink-3">
          题目导航（已答 {answeredCount}/{totalQuestions}）
          {showWrongOnly && wrongCount > 0 ? ' · 错题回顾模式' : ''}
        </div>
        <div className="flex flex-wrap gap-1.5">
          {filteredQuestions.map((q, idx) => {
            const id = getQuestionId(q, questions.indexOf(q))
            const ans = answers.get(id)
            const answered = ans != null
            const correct = answered && OPTION_LABELS[ans] === q.answer
            return (
              <button
                key={id}
                onClick={() => jumpToQuestion(idx)}
                title={`第 ${idx + 1} 题`}
                className={`h-7 w-7 rounded-md text-[11px] font-semibold tabular-nums transition-all duration-100 ${
                  idx === currentIndex
                    ? 'scale-110 bg-accent text-white'
                    : answered
                      ? correct
                        ? 'bg-correct-bg text-correct'
                        : 'bg-wrong-bg text-wrong'
                      : 'bg-ink/[0.05] text-ink-2 hover:bg-ink/10 dark:bg-white/[0.08] dark:hover:bg-white/15'
                } ${bookmarks.has(id) ? 'ring-2 ring-star/70' : ''}`}
              >
                {idx + 1}
              </button>
            )
          })}
        </div>
        <div className="mt-3 text-center text-[11.5px] text-ink-3">
          键盘作答：A–D 选择 · ↵ 提交 / 下一题 · ← → 切题
        </div>
      </div>
    </div>
  )
}

function wrongShown(answers: Map<string, number | null>, questions: QuizQuestion[]): number {
  let n = 0
  questions.forEach((q, i) => {
    const a = answers.get(getQuestionId(q, i))
    if (a != null && OPTION_LABELS[a] !== q.answer) n++
  })
  return n
}

function Badge({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return (
    <span className={`rounded-full border px-2.5 py-0.5 text-[12px] font-medium ${className}`}>
      {children}
    </span>
  )
}

function CheckIcon({ className = '' }: { className?: string }) {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className={`shrink-0 ${className}`}>
      <path d="m5 12.5 4.5 4.5L19 7" />
    </svg>
  )
}

function CrossIcon({ className = '' }: { className?: string }) {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" className={`shrink-0 ${className}`}>
      <path d="M6 6l12 12M18 6 6 18" />
    </svg>
  )
}
